// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package spec

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/jongio/azd-core/editor"
	"github.com/jongio/azd-core/fileutil"
)

const (
	// DocsDir is the directory where docs are stored
	DocsDir = "docs"
	// SpecFile is the name of the spec file
	SpecFile = "spec.md"
	// MetadataFile tracks copilot-related file locations
	MetadataFile = ".copilot.json"
)

// Metadata tracks locations of copilot-generated files
type Metadata struct {
	SpecFile       string   `json:"specFile"`
	CheckpointDir  string   `json:"checkpointDir"`
	GeneratedFiles []string `json:"generatedFiles,omitempty"`
}

// DefaultMetadata returns the default metadata configuration
func DefaultMetadata() *Metadata {
	return &Metadata{
		SpecFile:      filepath.Join(DocsDir, SpecFile),
		CheckpointDir: filepath.Join(DocsDir, "checkpoints"),
	}
}

// LoadMetadata loads metadata from the workspace root
func LoadMetadata() (*Metadata, error) {
	data, err := os.ReadFile(MetadataFile)
	if err != nil {
		return DefaultMetadata(), nil // Return defaults if not found
	}
	var m Metadata
	if err := json.Unmarshal(data, &m); err != nil {
		return DefaultMetadata(), nil
	}
	return &m, nil
}

// SaveMetadata saves metadata to the workspace root
func SaveMetadata(m *Metadata) error {
	return fileutil.AtomicWriteJSON(MetadataFile, m)
}

// Spec represents the application specification
type Spec struct {
	Name           string
	Description    string
	Mode           string // prototype or production
	CreatedAt      time.Time
	Architecture   string // mermaid diagram
	Services       []Service
	AzureResources []AzureResource
	CostEstimate   CostEstimate
	Goals          []string
	NonGoals       []string
}

// Service represents an application service
type Service struct {
	Name        string
	Type        string // api, web, worker, function
	Language    string
	Framework   string
	Description string
}

// AzureResource represents an Azure resource to be provisioned
type AzureResource struct {
	Name        string
	Type        string
	SKU         string
	Purpose     string
	FreeTier    bool
	MonthlyCost float64
}

// CostEstimate represents the estimated Azure costs
type CostEstimate struct {
	Monthly     float64
	Yearly      float64
	FreeTierMax float64 // if using all free tiers
	Confidence  string  // high, medium, low
}

// GetSpecPath returns the path to the spec file in the project
func GetSpecPath() string {
	m, _ := LoadMetadata()
	return m.SpecFile
}

// Path returns the path to the spec file
func Path() string {
	return GetSpecPath()
}

// Exists checks if a spec file exists
func Exists() bool {
	_, err := os.Stat(GetSpecPath())
	return err == nil
}

// Read reads the spec file and returns its content
func Read() (string, error) {
	content, err := os.ReadFile(GetSpecPath())
	if err != nil {
		return "", fmt.Errorf("failed to read spec: %w", err)
	}
	return string(content), nil
}

// OpenInEditor opens the spec file in the default editor
func OpenInEditor() error {
	return editor.Open(GetSpecPath())
}

// Write writes the spec content to the spec file
func Write(content string) error {
	specPath := GetSpecPath()
	dir := filepath.Dir(specPath)

	// Ensure directory exists
	if err := fileutil.EnsureDir(dir); err != nil {
		return fmt.Errorf("failed to create spec directory: %w", err)
	}

	if err := fileutil.AtomicWriteFile(specPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write spec: %w", err)
	}

	return nil
}

// GenerateMarkdown generates a markdown spec from the Spec struct
func GenerateMarkdown(s *Spec) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Application Specification\n\n")
	sb.WriteString(fmt.Sprintf("> Generated by Azure Copilot CLI on %s\n\n", s.CreatedAt.Format("2006-01-02 15:04")))

	// Overview
	sb.WriteString("## Overview\n\n")
	sb.WriteString(fmt.Sprintf("**Name:** %s\n\n", s.Name))
	sb.WriteString(fmt.Sprintf("**Description:** %s\n\n", s.Description))
	sb.WriteString(fmt.Sprintf("**Mode:** %s\n\n", s.Mode))

	// Goals
	if len(s.Goals) > 0 {
		sb.WriteString("## Goals\n\n")
		for _, goal := range s.Goals {
			sb.WriteString(fmt.Sprintf("- %s\n", goal))
		}
		sb.WriteString("\n")
	}

	// Non-Goals
	if len(s.NonGoals) > 0 {
		sb.WriteString("## Non-Goals\n\n")
		for _, nonGoal := range s.NonGoals {
			sb.WriteString(fmt.Sprintf("- %s\n", nonGoal))
		}
		sb.WriteString("\n")
	}

	// Architecture
	if s.Architecture != "" {
		sb.WriteString("## Architecture\n\n")
		sb.WriteString("```mermaid\n")
		sb.WriteString(s.Architecture)
		sb.WriteString("\n```\n\n")
	}

	// Services
	if len(s.Services) > 0 {
		sb.WriteString("## Services\n\n")
		sb.WriteString("| Service | Type | Language | Framework | Description |\n")
		sb.WriteString("|---------|------|----------|-----------|-------------|\n")
		for _, svc := range s.Services {
			sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
				svc.Name, svc.Type, svc.Language, svc.Framework, svc.Description))
		}
		sb.WriteString("\n")
	}

	// Azure Resources
	if len(s.AzureResources) > 0 {
		sb.WriteString("## Azure Resources\n\n")
		sb.WriteString("| Resource | Type | SKU | Purpose | Free Tier | Monthly Cost |\n")
		sb.WriteString("|----------|------|-----|---------|-----------|-------------|\n")
		for _, res := range s.AzureResources {
			freeTier := "❌"
			if res.FreeTier {
				freeTier = "✅"
			}
			cost := fmt.Sprintf("$%.2f", res.MonthlyCost)
			if res.FreeTier {
				cost = "Free"
			}
			sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s |\n",
				res.Name, res.Type, res.SKU, res.Purpose, freeTier, cost))
		}
		sb.WriteString("\n")
	}

	// Cost Estimate
	sb.WriteString("## Cost Estimate\n\n")
	sb.WriteString("| Timeframe | Estimated Cost |\n")
	sb.WriteString("|-----------|----------------|\n")
	sb.WriteString(fmt.Sprintf("| Monthly | $%.2f |\n", s.CostEstimate.Monthly))
	sb.WriteString(fmt.Sprintf("| Yearly | $%.2f |\n", s.CostEstimate.Yearly))
	if s.CostEstimate.FreeTierMax > 0 {
		sb.WriteString(fmt.Sprintf("| With Free Tiers | $%.2f |\n", s.CostEstimate.FreeTierMax))
	}
	sb.WriteString(fmt.Sprintf("\n*Confidence: %s*\n\n", s.CostEstimate.Confidence))

	// Instructions
	sb.WriteString("---\n\n")
	sb.WriteString("## Next Steps\n\n")
	sb.WriteString("1. Review this specification\n")
	sb.WriteString("2. Edit any sections that need changes\n")
	sb.WriteString("3. Run `azd copilot build --approve` to proceed with generation\n")
	sb.WriteString("4. Or run `azd copilot build` to regenerate the spec\n")

	return sb.String()
}

// GeneratePrompt creates a spec generation prompt for Copilot
func GeneratePrompt(description string, mode string) string {
	var sb strings.Builder

	sb.WriteString("# Generate Application Specification\n\n")
	sb.WriteString(fmt.Sprintf("**User Request:** %s\n\n", description))
	sb.WriteString(fmt.Sprintf("**Mode:** %s\n\n", mode))

	sb.WriteString("## Instructions\n\n")
	sb.WriteString("Analyze the user's request and generate a comprehensive application specification.\n\n")
	sb.WriteString("Save the specification to `docs/spec.md` with this structure:\n\n")

	sb.WriteString("```markdown\n")
	sb.WriteString("# Application Specification\n\n")
	sb.WriteString("> Generated by Azure Copilot CLI on [date]\n\n")
	sb.WriteString("## Overview\n")
	sb.WriteString("**Name:** [project name]\n")
	sb.WriteString("**Description:** [one paragraph]\n")
	sb.WriteString("**Mode:** [prototype|production]\n\n")
	sb.WriteString("## Goals\n")
	sb.WriteString("- [goal 1]\n")
	sb.WriteString("- [goal 2]\n\n")
	sb.WriteString("## Non-Goals\n")
	sb.WriteString("- [what this won't do]\n\n")
	sb.WriteString("## Architecture\n")
	sb.WriteString("```mermaid\n")
	sb.WriteString("graph TB\n")
	sb.WriteString("  [architecture diagram]\n")
	sb.WriteString("```\n\n")
	sb.WriteString("## Services\n")
	sb.WriteString("| Service | Type | Language | Framework | Description |\n")
	sb.WriteString("|---------|------|----------|-----------|-------------|\n\n")
	sb.WriteString("## Azure Resources\n")
	sb.WriteString("| Resource | Type | SKU | Purpose | Free Tier | Monthly Cost |\n")
	sb.WriteString("|----------|------|-----|---------|-----------|-------------|\n\n")
	sb.WriteString("## Cost Estimate\n")
	sb.WriteString("| Timeframe | Estimated Cost |\n")
	sb.WriteString("|-----------|----------------|\n")
	sb.WriteString("| Monthly | $X.XX |\n")
	sb.WriteString("| Yearly | $X.XX |\n")
	sb.WriteString("```\n\n")

	if mode == "prototype" {
		sb.WriteString("### Prototype Mode Guidelines\n\n")
		sb.WriteString("- Use free tiers wherever possible\n")
		sb.WriteString("- Minimize complexity\n")
		sb.WriteString("- Single environment\n")
		sb.WriteString("- Basic error handling\n")
		sb.WriteString("- Smoke tests only\n\n")
	} else {
		sb.WriteString("### Production Mode Guidelines\n\n")
		sb.WriteString("- Use appropriately sized SKUs\n")
		sb.WriteString("- Include monitoring and alerting\n")
		sb.WriteString("- Multiple environments (dev, staging, prod)\n")
		sb.WriteString("- Comprehensive error handling\n")
		sb.WriteString("- Full test coverage (80%+)\n")
		sb.WriteString("- Security hardening\n\n")
	}

	sb.WriteString("After creating the spec file, tell the user to review it and run:\n")
	sb.WriteString("`azd copilot build --approve` to proceed with code generation.\n")

	return sb.String()
}
